name: discord_interactions_test
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.14.4 <3.0.0"

dependencies:
  discord_interactions: ^0.0.5
  shelf_router: ^1.1.2
  shelf_web_socket: ^1.0.1

dev_dependencies:
  lints: ^1.0.0
